# Generated by Django 5.0.2 on 2025-04-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='orientation',
            field=models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait'), ('square', 'Square')], default='landscape', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
