# Generated by Django 5.0.2 on 2025-05-12 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_savedvideo_watchhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchhistory',
            options={'ordering': ['-watched_at']},
        ),
    ]
