# Generated by Django 5.0.2 on 2025-04-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('subscriber', 'New Subscriber'), ('reply', 'Reply to Comment'), ('comment', 'New Comment')], max_length=20),
        ),
    ]
