# Generated by Django 5.0.2 on 2025-05-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userprofile_ban_reason_accountappeal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('purple', 'Purple'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange')], default='default', max_length=10),
        ),
    ]
